"""posts table

Revision ID: 34738fed991b
Revises: 05758d953bcb
Create Date: 2018-08-10 20:33:32.032035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34738fed991b'
down_revision = '05758d953bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('post', sa.String(length=400), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_date_time'), 'post', ['date_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_date_time'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
